# Generated by Django 2.2 on 2021-05-31 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('number_image', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=1)),
                ('result_client', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RequestImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(upload_to='img/%y')),
                ('status', models.IntegerField(default=1)),
                ('result_image', models.CharField(max_length=1000)),
                ('request_image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file_uploader.RequestClient')),
            ],
        ),
    ]
